package frame;


import domain.User;
import frame.ExamFrame2;
import java.util.*;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.IOUtil;
import util.QuestionUtil;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 10756
 */
public class examFrame extends javax.swing.JFrame {
    private IOUtil ioutil  = IOUtil.getIOUtil();
    private User user;
     List<List<String>> data; 
     int index=0;  //题目的索引
    
     public examFrame() {
        initComponents();
        user = IOUtil.getUser();
        lblStuID.setText(lblStuID.getText() + user.getUserID());
        lblName.setText(lblName.getText() + user.getUserName());
        lblClass.setText(lblClass.getText() + user.getGroupName());
        lblSubject.setText(lblSubject.getText() + QuestionUtil.getName());
        data = QuestionUtil.getChoice().getItems();
        txtExam.setLineWrap(true);        //激活自动换行功能 
        txtExam.setWrapStyleWord(true);   // 激活断行不断字功能
        showTextData(index);
        showChoiceData(index);
        Null.setVisible(false);
   }
     
    public void showTextData(int index){
        if(data==null || data.size()==0){
            JOptionPane.showMessageDialog(null, "目前数据为空","系统提示",JOptionPane.WARNING_MESSAGE);
        }else{
            txtExam.setText(data.get(index).get(1));
            txtA.setText(data.get(index).get(2));
            txtB.setText(data.get(index).get(3));
            txtC.setText(data.get(index).get(4));
            txtD.setText(data.get(index).get(5));
        }
        //调用锁定文本框的方法
        lockText();
    }
    
   
   
    private void setButton(char c) {  //选择选项
        if (c == 'A') {
            A.setSelected(true);
        } else if (c == 'B') {
            B.setSelected(true);
        } else if (c == 'C') {
            C.setSelected(true);
        } else if (c == 'D') {
            D.setSelected(true);
        } 
    }
    
    
    //锁定文本框
    public void lockText(){
        txtExam.setEnabled(false);
        txtA.setEnabled(false);
        txtB.setEnabled(false);
        txtC.setEnabled(false);
        txtD.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtExam = new javax.swing.JTextArea();
        A = new javax.swing.JRadioButton();
        B = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        D = new javax.swing.JRadioButton();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnJudge = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        AScrollPane = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        BScrollPane = new javax.swing.JScrollPane();
        txtB = new javax.swing.JTextArea();
        CScrollPane = new javax.swing.JScrollPane();
        txtC = new javax.swing.JTextArea();
        DScrollPane = new javax.swing.JScrollPane();
        txtD = new javax.swing.JTextArea();
        lblChoice = new javax.swing.JLabel();
        lblStuID = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        lblSubject = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        Null = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtExam.setColumns(20);
        txtExam.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtExam.setRows(5);
        txtExam.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtExam.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(txtExam);

        choice.add(A);
        A.setText("A");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        choice.add(B);
        B.setText("B");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });

        choice.add(C);
        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        choice.add(D);
        D.setText("D");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });

        btnLast.setText("<");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnJudge.setText("判断题");
        btnJudge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJudgeActionPerformed(evt);
            }
        });

        btnSubmit.setText("提交试卷");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        txtA.setColumns(20);
        txtA.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        txtA.setRows(5);
        txtA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtA.setSelectionColor(new java.awt.Color(0, 0, 0));
        AScrollPane.setViewportView(txtA);

        txtB.setColumns(20);
        txtB.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        txtB.setRows(5);
        txtB.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtB.setSelectionColor(new java.awt.Color(0, 0, 0));
        BScrollPane.setViewportView(txtB);

        txtC.setColumns(20);
        txtC.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        txtC.setRows(5);
        txtC.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtC.setSelectionColor(new java.awt.Color(0, 0, 0));
        CScrollPane.setViewportView(txtC);

        txtD.setColumns(20);
        txtD.setFont(new java.awt.Font("Monospaced", 0, 15)); // NOI18N
        txtD.setRows(5);
        txtD.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtD.setSelectionColor(new java.awt.Color(0, 0, 0));
        DScrollPane.setViewportView(txtD);

        lblChoice.setText("   选择题");

        lblStuID.setText("学号：");

        lblClass.setText("班级：");

        lblSubject.setText("考试科目：");

        lblName.setText("姓名：");

        choice.add(Null);
        Null.setText("jRadioButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnJudge, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblClass, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSubject, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStuID, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(A)
                                    .addComponent(B)
                                    .addComponent(D)
                                    .addComponent(C))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Null))))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStuID))
                        .addGap(18, 18, 18)
                        .addComponent(lblClass)
                        .addGap(36, 36, 36)
                        .addComponent(lblName)
                        .addGap(40, 40, 40)
                        .addComponent(lblSubject)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnJudge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(C)
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D)
                            .addComponent(DScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Null))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
         if(index>0){
            index--;
            //再调用文本框中显示数据的方法
            showTextData(index);
            showChoiceData(index);
        }else{
            //弹出对话框
            JOptionPane.showMessageDialog(null,"已经是第一条数据了","系统提示",JOptionPane.INFORMATION_MESSAGE);
        }                                      
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnJudgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJudgeActionPerformed
        ExamFrame2 frm=new ExamFrame2();
        frm.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_btnJudgeActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
          if(index<data.size()-1){
            index++;
            //再调用文本框中显示数据的方法
            showTextData(index);
            showChoiceData(index);
        }else{
            //弹出对话框
            JOptionPane.showMessageDialog(null,"已经是最后一条数据了","系统提示",JOptionPane.INFORMATION_MESSAGE);
        }  
    }//GEN-LAST:event_btnNextActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        QuestionUtil.setChoiceAnswerItem(index, "A");
    }//GEN-LAST:event_AActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        QuestionUtil.setChoiceAnswerItem(index, "B");
    }//GEN-LAST:event_BActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        QuestionUtil.setChoiceAnswerItem(index, "C");
    }//GEN-LAST:event_CActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        QuestionUtil.setChoiceAnswerItem(index, "D");
    }//GEN-LAST:event_DActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        int opt = JOptionPane.showConfirmDialog(null ,"请确认是否提交试卷?", "确认信息",JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION) {
            new FrmEnd().setVisible(true);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(examFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(examFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(examFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(examFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new examFrame().setVisible(true);
            }
        });
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton A;
    private javax.swing.JScrollPane AScrollPane;
    private javax.swing.JRadioButton B;
    private javax.swing.JScrollPane BScrollPane;
    private javax.swing.JRadioButton C;
    private javax.swing.JScrollPane CScrollPane;
    private javax.swing.JRadioButton D;
    private javax.swing.JScrollPane DScrollPane;
    private javax.swing.JRadioButton Null;
    private javax.swing.JButton btnJudge;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup choice;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChoice;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblStuID;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JTextArea txtA;
    private javax.swing.JTextArea txtB;
    private javax.swing.JTextArea txtC;
    private javax.swing.JTextArea txtD;
    private javax.swing.JTextArea txtExam;
    // End of variables declaration//GEN-END:variables

    private void showChoiceData(int index) {
        String choice = QuestionUtil.getChoiceAnswerItem(index);
        if(choice != null) {
            switch (choice) {
                case "" : Null.setSelected(true);break;
                case "A" : A.setSelected(true);break;
                case "B" : B.setSelected(true);break;
                case "C" : C.setSelected(true);break;
                case "D" : D.setSelected(true);break;
            }
        }
    }
}
