package frame;

import domain.User;
import java.util.List;
import util.IOUtil;
import util.QuestionUtil;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 李梓颖
 */
public class FrmEnd extends javax.swing.JFrame {

    /**
     * Creates new form frm_end
     */
    private User user;
    
    public FrmEnd() {
        initComponents();
        setLocationRelativeTo(null);
        user = IOUtil.getUser();
        txtUserID.setText(user.getUserID());
        txtName.setText(user.getUserName());
        txtClass.setText(user.getGroupName());
        txtMajor.setText(QuestionUtil.getName());
        txtScore.setText(Integer.toString(getScore()));
        lockText();
        showData();
    }
    
    private void lockText() {
        txtUserID.setEditable(false);
        txtName.setEditable(false);
        txtClass.setEditable(false);
        txtMajor.setEditable(false);
        txtScore.setEditable(false);
        txaSelect.setEditable(false);
        txaJudge.setEditable(false);
    }
    
    private void showData() {
        List<List<String>> choice = QuestionUtil.getChoice().getItems();
        for(int i = 0; i < choice.size(); i++) {
            txaSelect.append(choice.get(i).get(1) + "\n");
            txaSelect.append(choice.get(i).get(2) + "\n");
            txaSelect.append(choice.get(i).get(3) + "\n");
            txaSelect.append(choice.get(i).get(4) + "\n");
            txaSelect.append(choice.get(i).get(5) + "\n");
            txaSelect.append("你的答案是：" + QuestionUtil.getChoiceAnswerItem(i) + "\n");
            txaSelect.append("正确答案答案是：" + choice.get(i).get(0) + "\n");
        }
        List<List<String>> trueOrFalse = QuestionUtil.getTrueOrFalse().getItems();
        for(int i = 0; i < trueOrFalse.size(); i++) {
            txaJudge.append(trueOrFalse.get(i).get(1) + "\n");
            txaJudge.append("你的答案是：" + QuestionUtil.getTrueOrFalseAnswerItem(i) + "\n");
            txaJudge.append("正确答案答案是：" + trueOrFalse.get(i).get(0) + "\n");
        }
    }
    
    private int getScore() {
        int cnt = 0;
        List<List<String>> choice = QuestionUtil.getChoice().getItems();
        for(int i = 0; i < choice.size(); i++) {
            if(choice.get(i).get(0).equals(QuestionUtil.getChoiceAnswerItem(i))) {
                cnt++;
            }
        }
        List<List<String>> trueOrFalse = QuestionUtil.getTrueOrFalse().getItems();
        for(int i = 0; i < trueOrFalse.size(); i++) {
            if(trueOrFalse.get(i).get(0).equals(QuestionUtil.getTrueOrFalseAnswerItem(i))) {
                cnt++;
            }
        }
        return cnt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStuMessage = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        lblMajor = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        txtUserID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtMajor = new javax.swing.JTextField();
        txtClass = new javax.swing.JTextField();
        lblPicture1 = new javax.swing.JLabel();
        lblExamMessage = new javax.swing.JLabel();
        pnlExamMessage = new javax.swing.JPanel();
        lblPicture2 = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        txtScore = new javax.swing.JTextField();
        lblScoureMessage = new javax.swing.JLabel();
        pnlScoreMessage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaSelect = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaJudge = new javax.swing.JTextArea();
        lblSelect = new javax.swing.JLabel();
        lblJudge = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("考试完成");

        lblStuMessage.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        lblStuMessage.setText("考生信息");

        lblName.setFont(new java.awt.Font("楷体", 0, 18)); // NOI18N
        lblName.setText("姓名");

        lblUserID.setFont(new java.awt.Font("楷体", 0, 18)); // NOI18N
        lblUserID.setText("学号");

        lblMajor.setFont(new java.awt.Font("楷体", 0, 18)); // NOI18N
        lblMajor.setText("考试科目");

        lblClass.setFont(new java.awt.Font("楷体", 0, 18)); // NOI18N
        lblClass.setText("班级");

        btnExit.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        btnExit.setText("考试结束，退出系统");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        txtUserID.setFont(new java.awt.Font("楷体", 0, 18)); // NOI18N
        txtUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIDActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("楷体", 0, 18)); // NOI18N

        txtMajor.setFont(new java.awt.Font("楷体", 0, 18)); // NOI18N

        txtClass.setFont(new java.awt.Font("楷体", 0, 18)); // NOI18N

        lblPicture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Frm_end_picture1.jpg"))); // NOI18N

        lblExamMessage.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        lblExamMessage.setText("考试信息");

        lblPicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Frm_end_picture2.jpeg"))); // NOI18N

        lblScore.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 102, 102));
        lblScore.setText("本次分数：");

        txtScore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlExamMessageLayout = new javax.swing.GroupLayout(pnlExamMessage);
        pnlExamMessage.setLayout(pnlExamMessageLayout);
        pnlExamMessageLayout.setHorizontalGroup(
            pnlExamMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExamMessageLayout.createSequentialGroup()
                .addContainerGap(396, Short.MAX_VALUE)
                .addGroup(pnlExamMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPicture2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlExamMessageLayout.createSequentialGroup()
                        .addComponent(lblScore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(526, 526, 526))
        );
        pnlExamMessageLayout.setVerticalGroup(
            pnlExamMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExamMessageLayout.createSequentialGroup()
                .addComponent(lblPicture2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlExamMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScore)
                    .addComponent(txtScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        lblScoureMessage.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        lblScoureMessage.setText("评分信息");

        txaSelect.setColumns(20);
        txaSelect.setRows(5);
        jScrollPane1.setViewportView(txaSelect);

        txaJudge.setColumns(20);
        txaJudge.setRows(5);
        jScrollPane2.setViewportView(txaJudge);

        lblSelect.setText("选择题");

        lblJudge.setText("判断题");

        javax.swing.GroupLayout pnlScoreMessageLayout = new javax.swing.GroupLayout(pnlScoreMessage);
        pnlScoreMessage.setLayout(pnlScoreMessageLayout);
        pnlScoreMessageLayout.setHorizontalGroup(
            pnlScoreMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScoreMessageLayout.createSequentialGroup()
                .addComponent(lblSelect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlScoreMessageLayout.createSequentialGroup()
                .addComponent(lblJudge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2))
        );
        pnlScoreMessageLayout.setVerticalGroup(
            pnlScoreMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScoreMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlScoreMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlScoreMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addGroup(pnlScoreMessageLayout.createSequentialGroup()
                        .addComponent(lblJudge)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblPicture1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtUserID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMajor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMajor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtClass, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblClass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblStuMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblExamMessage)
                    .addComponent(pnlScoreMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblScoureMessage)
                    .addComponent(pnlExamMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStuMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPicture1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblExamMessage)
                .addGap(365, 365, 365)
                .addComponent(lblUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(pnlExamMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lblScoureMessage)
                .addGap(15, 15, 15)
                .addComponent(pnlScoreMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIDActionPerformed

    private void txtScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScoreActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblExamMessage;
    private javax.swing.JLabel lblJudge;
    private javax.swing.JLabel lblMajor;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPicture1;
    private javax.swing.JLabel lblPicture2;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblScoureMessage;
    private javax.swing.JLabel lblSelect;
    private javax.swing.JLabel lblStuMessage;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JPanel pnlExamMessage;
    private javax.swing.JPanel pnlScoreMessage;
    private javax.swing.JTextArea txaJudge;
    private javax.swing.JTextArea txaSelect;
    private javax.swing.JTextField txtClass;
    private javax.swing.JTextField txtMajor;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtScore;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
