/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frame;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
import util.IOUtil;

/**
 *
 * @author 李梓颖
 */
public class FrmManage extends javax.swing.JFrame {
    private static Logger logger = Logger.getLogger(FrmManage.class);
    private Vector<String> title;
    private Vector<Vector<String>> data;
    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultTableModel dtm1 = new DefaultTableModel();
    private IOUtil ioutil = IOUtil.getIOUtil();
    private Vector<String> stitle;
    private Vector<Vector<String>> sdata;
    /**
     * Creates new form Frm_mannage
     */
    public FrmManage() {
        initComponents();
        setLocationRelativeTo(null);
        data = new Vector<>();
        title = new Vector<>();
        sdata = new Vector<>();
        stitle = new Vector<>();
        title.add("班级号");
        title.add("班级名称");
        stitle.add("用户名");
        stitle.add("学号");
        tblClass.setModel(dtm);
        tblStudent.setModel(dtm1);
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgStudent = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        dlgCreate = new javax.swing.JDialog();
        lblClassName = new javax.swing.JLabel();
        txtClassName = new javax.swing.JTextField();
        btnYes = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        dlgChange = new javax.swing.JDialog();
        lblClassName1 = new javax.swing.JLabel();
        txtClassName1 = new javax.swing.JTextField();
        btnYes1 = new javax.swing.JButton();
        btnNo1 = new javax.swing.JButton();
        lblClassID = new javax.swing.JLabel();
        txtClassID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClass = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        dlgStudent.setTitle("学生信息");
        dlgStudent.setMinimumSize(new java.awt.Dimension(450, 450));

        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "用户名", "学号"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblStudent);

        javax.swing.GroupLayout dlgStudentLayout = new javax.swing.GroupLayout(dlgStudent.getContentPane());
        dlgStudent.getContentPane().setLayout(dlgStudentLayout);
        dlgStudentLayout.setHorizontalGroup(
            dlgStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        dlgStudentLayout.setVerticalGroup(
            dlgStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        dlgCreate.setTitle("新建班级");
        dlgCreate.setMinimumSize(new java.awt.Dimension(450, 170));

        lblClassName.setText("班级名称");

        txtClassName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassNameActionPerformed(evt);
            }
        });

        btnYes.setText("确定");
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });

        btnNo.setText("取消");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgCreateLayout = new javax.swing.GroupLayout(dlgCreate.getContentPane());
        dlgCreate.getContentPane().setLayout(dlgCreateLayout);
        dlgCreateLayout.setHorizontalGroup(
            dlgCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCreateLayout.createSequentialGroup()
                .addGroup(dlgCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgCreateLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblClassName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClassName, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addGroup(dlgCreateLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnYes, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dlgCreateLayout.setVerticalGroup(
            dlgCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCreateLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(dlgCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassName)
                    .addComponent(txtClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(dlgCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYes)
                    .addComponent(btnNo))
                .addGap(38, 38, 38))
        );

        dlgChange.setTitle("修改班级");
        dlgChange.setMinimumSize(new java.awt.Dimension(450, 200));

        lblClassName1.setText("新班级名称");

        txtClassName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassName1ActionPerformed(evt);
            }
        });

        btnYes1.setText("确定");
        btnYes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYes1ActionPerformed(evt);
            }
        });

        btnNo1.setText("取消");
        btnNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNo1ActionPerformed(evt);
            }
        });

        lblClassID.setText("班级号");

        javax.swing.GroupLayout dlgChangeLayout = new javax.swing.GroupLayout(dlgChange.getContentPane());
        dlgChange.getContentPane().setLayout(dlgChangeLayout);
        dlgChangeLayout.setHorizontalGroup(
            dlgChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgChangeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgChangeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnYes1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgChangeLayout.createSequentialGroup()
                        .addGroup(dlgChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClassName1)
                            .addGroup(dlgChangeLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblClassID)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dlgChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtClassName1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(txtClassID))))
                .addContainerGap())
        );
        dlgChangeLayout.setVerticalGroup(
            dlgChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgChangeLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(dlgChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassID)
                    .addComponent(txtClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(dlgChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClassName1)
                    .addComponent(txtClassName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(dlgChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYes1)
                    .addComponent(btnNo1))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("信息管理");

        tblClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "班级ID", "班级名称"
            }
        ));
        jScrollPane1.setViewportView(tblClass);

        btnCreate.setText("新建班级");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnChange.setText("修改班级");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnView.setText("查看班级成员信息");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        showStudentData(data.get(tblClass.getSelectedRow()).get(0));
        dlgStudent.setVisible(true);
        dlgStudent.toFront();
        dlgStudent.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        txtClassName.setText("");
        dlgCreate.setVisible(true);
        dlgCreate.toFront();
        dlgCreate.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        ioutil.writeln("newgroup " + txtClassName.getText());
        String ret = ioutil.readln();
        if(ret.equals("NG1")) {
            JOptionPane.showMessageDialog(null, "创建班级成功!","系统提示",JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "创建班级失败!","系统提示",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnYesActionPerformed

    private void txtClassNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassNameActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        // TODO add your handling code here:
        dlgCreate.dispose(); 
        
    }//GEN-LAST:event_btnNoActionPerformed

    private void txtClassName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassName1ActionPerformed

    private void btnYes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYes1ActionPerformed
        ioutil.writeln("changegroupname" + " " + txtClassID.getText() + " "+ txtClassName1.getText());
        String ret = ioutil.readln();
        if(ret.equals("CG1")) {
            JOptionPane.showMessageDialog(null, "修改班级成功!","系统提示",JOptionPane.INFORMATION_MESSAGE);
            showTableData();
            dlgChange.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "修改班级失败!","系统提示",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnYes1ActionPerformed

    private void btnNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNo1ActionPerformed
        // TODO add your handling code here:
        dlgChange.dispose();
    }//GEN-LAST:event_btnNo1ActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        txtClassID.setText("");
        txtClassName1.setText("");
        dlgChange.setVisible(true);
        dlgChange.toFront();
        dlgChange.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnNo1;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnYes;
    private javax.swing.JButton btnYes1;
    private javax.swing.JDialog dlgChange;
    private javax.swing.JDialog dlgCreate;
    private javax.swing.JDialog dlgStudent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClassID;
    private javax.swing.JLabel lblClassName;
    private javax.swing.JLabel lblClassName1;
    private javax.swing.JTable tblClass;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextField txtClassID;
    private javax.swing.JTextField txtClassName;
    private javax.swing.JTextField txtClassName1;
    // End of variables declaration//GEN-END:variables

    private void showTableData() {
        ioutil.writeln("getgroups");
        String s = ioutil.readln();
        if(s.equals("GG1")) {
            String json = ioutil.readln();
            ObjectMapper objectMapper =  new ObjectMapper();
            List<Map<String, String>> courses = null;
            try {
                courses = objectMapper.readValue(json, new TypeReference<List<Map<String, String>>>(){});
            } catch (JsonProcessingException ex) {
                logger.error(ex);
            }
            data.clear();
            for(Map<String, String> item : courses) {
                Vector<String> row = new Vector<>();
                row.add(item.get("groupid"));
                row.add(item.get("groupname"));
                data.add(row);
            }
        } else {
            JOptionPane.showMessageDialog(null, "无法获取信息!请重新登录","系统提示",JOptionPane.INFORMATION_MESSAGE);
        }
        dtm.setDataVector(data, title);
    }

    private void showStudentData(String groupid) {
        ioutil.writeln("getusers" + " " + groupid);
        String s = ioutil.readln();
        if(s.equals("GU1")) {
            String json = ioutil.readln();
            ObjectMapper objectMapper =  new ObjectMapper();
            List<Map<String, String>> courses = null;
            try {
                courses = objectMapper.readValue(json, new TypeReference<List<Map<String, String>>>(){});
            } catch (JsonProcessingException ex) {
                logger.error(ex);
            }
            sdata.clear();
            for(Map<String, String> item : courses) {
                Vector<String> row = new Vector<>();
                row.add(item.get("userName"));
                row.add(item.get("userID"));
                sdata.add(row);
            }
        } else {
            JOptionPane.showMessageDialog(null, "无法获取信息!请重新登录","系统提示",JOptionPane.INFORMATION_MESSAGE);
        }
        dtm1.setDataVector(sdata, stitle);
    }
}
